name 'ntp'
maintainer 'Nate Delgado'
maintainer_email 'goatscript@gmail.com'
license 'all_rights'
description 'Installs/Configures ntp'
long_description 'Installs/Configures ntp'
version '0.1.0'
depends 'windows'
